<a href="https://colab.research.google.com/github/phon1e/pytorch_practice/blob/main/pytorch_ztm00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!nvidia-smi

Thu Jan 19 11:49:32 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   70C    P0    31W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.13.1+cu116


## Introduction to tensor

### Creating tensors

PyTorch tensors are created using torch.Tensor() = https://pytorch.org/docs/stable/tensors.html


In [ ]:
# scalar 
scalar = torch.tensor(7)

print(scalar)

tensor(7)


In [ ]:
scalar.ndim

0

In [ ]:
#get tensor back as py int 

scalar.item()

7

In [ ]:
#vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
print(f"{vector.ndim} {vector.shape}")


1 torch.Size([2])


In [ ]:
#Matrix
MAT = torch.tensor([[7, 8],
                   [9, 10]])
MAT

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MAT.ndim

2

In [ ]:
MAT[1]

tensor([ 9, 10])

In [ ]:
#tensor
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6]
                        ,[7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random tensors 

Why random tensors?

random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> update random numbers

Torch random tebsors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [ ]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)

In [ ]:
random_tensor

tensor([[0.1357, 0.0826, 0.6938, 0.5033],
        [0.4533, 0.0184, 0.5350, 0.0751],
        [0.3094, 0.9810, 0.2627, 0.1642]])

In [ ]:
random_tensor.ndim

2

In [ ]:
# Create a random tensor with similar shape to an image tensor 
random_image_size_tensor = torch.rand(224, 224, 3) # h w color_ch
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [ ]:
#Create a tensor of all zeros 

zeros = torch.zeros(size= (3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#  Create a tensor of all ones
ones = torch.ones(size= (3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

### Create a range of tensors and tensors-like

In [ ]:
# Use torch.range() and get deprecated message just use torch.arange() instead

one_to_ten = torch.arange(start=0, end=11, step= 1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
torch.__version__

'1.13.1+cu116'

In [ ]:
# Creating tensors like
ten_zeros = torch.zeros_like(input =one_to_ten)

In [ ]:
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
t1 = torch.arange(start = 0, end= 21, step = 2)
t1

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
cpy_t1 = torch.ones_like(t1)
cpy_t1

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### Tensor datatypes

**Note** Tensor datatypes is one of the 3 of errors you'll run into with Pytorch & dl:
* 1. Tensors not right dtype
* 2. Tensors not right shape
* 3. Tensors not on the right device

dtype : datatype 16/32/64 float single pos = 32bit half = 16bit double=64

device : cpu / cuda
                                                requires_grad : track gradient of tensors 


In [ ]:
#float 32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None, #dtype = datatype 16/32/64 float single pos = 32bit half = 16bit double=64
                                                device = None, #cpu / cuda
                                                requires_grad = False) # track gradient of tensors 
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3, 6, 9], dtype= torch.long)
int_32_tensor

tensor([3, 6, 9])

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting info from tensors

1. Tensors not right dtype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [ ]:
# Creating a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.3190, 0.7699, 0.0304, 0.9402],
        [0.6254, 0.4552, 0.8635, 0.5186],
        [0.1111, 0.7397, 0.9841, 0.0857]])

In [ ]:
print(some_tensor)
nl = '\n'
print(f"Datatype: {some_tensor.dtype}{nl}Shape: {some_tensor.shape}{nl}Device:{some_tensor.device}")

tensor([[0.3190, 0.7699, 0.0304, 0.9402],
        [0.6254, 0.4552, 0.8635, 0.5186],
        [0.1111, 0.7397, 0.9841, 0.0857]])
Datatype: torch.float32
Shape: torch.Size([3, 4])
Device:cpu


### Manipulating Tensors (tensors operations)

Tensor opertions include:
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [ ]:
# Create a tensor
tensor = torch.tensor([1, 2, 3])
tensor+ 10

tensor([11, 12, 13])

In [ ]:
tensor * 10

tensor([10, 20, 30])

In [ ]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [ ]:
tensor - 10

tensor([-9, -8, -7])

In [ ]:
#Try in-built function
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplication in nn and double

1. Element-wise mul
2. Matrix mul 

There are 2 main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions**  must match:
* ` (3, 2) @ (3 , 2)` won't work
* ` (2, 3) @ (3 , 2)` will work
* ` (3, 2) @ (2 , 3)` will work
 
2. The resulting mat has the shape of the **outer dim**:
* `(2, 3) @ (3, 2)` --> `(2,2)`
* `(3, 2) @ (2 , 3)` --> `(3,3)`

In [ ]:
# eg 
torch.matmul(torch.rand(3,2), torch.rand(2,3 ))

tensor([[0.2819, 0.1264, 0.3969],
        [0.4491, 0.5272, 0.4388],
        [0.5980, 0.5632, 0.6667]])

In [ ]:
# element wise mul
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Matrix mul
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
# Matrix mul by hand
1*1 + 2*2 + 3*3

14

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 344 µs, sys: 729 µs, total: 1.07 ms
Wall time: 5.38 ms


In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 41 µs, sys: 8 µs, total: 49 µs
Wall time: 51.5 µs


tensor(14)

### One of the most common errors in dl is shape errors 

In [ ]:
# Shapes for mat mul
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])


tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

##torch.mm(tensor_A, tensor_B) # torch.mm == torch.matmul err cause inner dim not match

In [ ]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix tensor shape issues, we can manipulate the shape of one of our tensors using transose

A **transpose** switch the axes or dim of a given tensor.

matmul visualize site : http://matrixmultiplication.xyz/

In [ ]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]), torch.Size([2, 3]))

In [ ]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]), torch.Size([3, 2]))

In [ ]:
torch.mm(tensor_A, tensor_B.T), torch.mm(tensor_A, tensor_B.T).shape

(tensor([[ 27,  30,  33],
         [ 61,  68,  75],
         [ 95, 106, 117]]), torch.Size([3, 3]))

## Finding the min, max, mean, sum etc (tensor aggregation)

In [ ]:
# Create a tensor
x = torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
#Find the min
torch.min(x)

tensor(1)

In [ ]:
#Find the max
torch.max(x)

tensor(91)

In [ ]:
#Find mean error with int32 - torch.mean() requires a tensor of float32 dtype 
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [ ]:
#Find the sum 
# same pick what ever prefer
torch.sum(x), x.sum()

(tensor(460), tensor(460))

## Finding the pos min and max

In [ ]:
#Find the pos in tensor that has the min value with argmin() -> return index pos of 
#target tensor where the min value occurs
x.argmin()

tensor(0)

In [ ]:
x.argmax()

tensor(9)

In [ ]:
x[9]

tensor(91)

In [ ]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

## Reshaping, stacking, squeezing and unsqeezing tensors 

* Reshaping - reshapes an input tensor to a defined shape.
* View - return a view of an input tensor of certain shape but keep the same memory as the origical tensor.
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack).
* Squeeze - removes all `1` dmin from a tensor.
* Unsqueeze - add a `1` dim to a target tensor.
* Permut - Return a view of the input with dim permuted(swapped) in a certain way.

In [ ]:
# Let's create a tensor 
import torch

x = torch.arange(1., 10.)

x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# add an extra dim
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
#Change the view 
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
#Changing z changes x cuz view of a tensor shares the same memory as the original of input
z[:, 0] =5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
x

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
# Stack tensors on top of each other 
x_stacked = torch.stack([x,x,x,x], dim= 1) #take list of tensor 
x_stacked 

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
# torch.squeeze() - removes all single dim 
print(f"Prev tensor: {x_reshaped}")
print(f"Prev shape : {x_reshaped.shape}")

#Remove extra dim
x_squeezed = x_reshaped.squeeze()
x_squuzed = x_reshaped.square()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape : {x_squeezed.shape}")
x_reshaped

Prev tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Prev shape : torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape : torch.Size([9])


tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# torch.unsqueeze() - add single dim to a target tensor at a specific dim
print(f"Prev target: {x_squeezed}")
print(f"Prev shape : {x_squeezed.shape}")

#Add an extra dim with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape : {x_unsqueezed.shape}")

Prev target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Prev shape : torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape : torch.Size([1, 9])


In [ ]:
#torch.permute - rearrange the dum of a specifiy order, permute == view == shape mem of 
x_original = torch.rand(size=(224,224,3)) # [h, w, color_ch]

#permute the original tensor to rearrange the axis (or dim) order
# let swap it 

x_permuted = x_original.permute(2, 0, 1)
x_original.shape, x_permuted.shape #[color_ch, h, w]

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

In [ ]:
x_original[0,0,0] = 1234
x_original[0,0,0], x_permuted[0,0,0] # same memory 

(tensor(1234.), tensor(1234.))

In [ ]:
x_reshaped.shape

torch.Size([1, 9])

In [ ]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
x_reshaped.squeeze().shape

torch.Size([9])

## Indexing (selecing data from tensors)

Indexing with PyTorch is similar to indexing with Numpy

In [ ]:
# Create a tensor 
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]), torch.Size([1, 3, 3]))

In [ ]:
#Let index on new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
#Let index on the middle bracket (dim= 1)
x[0][0], x[0,0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [ ]:
x[0,0,0], x[0,2,2]

(tensor(1), tensor(9))

In [ ]:
#u can also use ":" to select "all" of a target dim
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
#Get all values of 0th and 1st dim but only index 1 of 2nd dim
x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
#Get all val of the 0dim but only the 1 indx value of 1st and 2nd dim
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
#Get index 0 of 0th and 1st dim and all val of 2nd dim
x[0,0,:]

tensor([1, 2, 3])

In [ ]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
#index x -> 9 
x[0,2,2]

tensor(9)

In [ ]:
#index x -> 3 6 9
x[:,:,2]

tensor([[3, 6, 9]])

## PyTorch tensors & NumPy

Numpy is a popular scientific python numerical computing lib.

And because of this, pytorch has funcitnality to interact with it.

* Data in NumPy, want in pytorch tensor -> `torch.from_numpy(ndarray)`
*PyTorch tensor -> Numpy-> `torch.Tensor.numpy()`

** Default dtype **

numpy - float64

torch - float32

In [ ]:
#Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.,8.)
tensor = torch.from_numpy(array) # when cvrt numpy to torch, torch reflects np default 
                                 #dtype of float64 (default torch float32)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array.dtype

dtype('float64')

In [ ]:
tensor.dtype

torch.float64

In [ ]:
torch.arange(1., 8.).dtype

torch.float32

In [ ]:
#Change the val of arr, what will this do to tensor

array = array + 1
array, tensor 

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
#Tensor to numpy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()

tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
numpy_tensor.dtype

dtype('float32')

**note**:

np -> torch = float64 because default np is float64 

torch -> np = float32 because default torch is float32

In [ ]:
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

In short how a nn learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again again and again....

To reduce the randomness in nn and pytorch comes the concept of a **random seed**

Essentially what the random does is "flavour" the randomness.

In [ ]:
import torch
#Create two random tensors

random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)


tensor([[0.6969, 0.5295, 0.6959, 0.2097],
        [0.9974, 0.5401, 0.8095, 0.7705],
        [0.8909, 0.2458, 0.3111, 0.7711]])
tensor([[0.0772, 0.8327, 0.6780, 0.1912],
        [0.9183, 0.8382, 0.6467, 0.7778],
        [0.8992, 0.6701, 0.4187, 0.1820]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
torch.rand(3,3)

tensor([[0.4475, 0.3448, 0.2188],
        [0.8847, 0.8632, 0.5662],
        [0.5180, 0.1102, 0.1337]])

In [ ]:
#Let's make some random but reproducible tensors
import torch

#Set the seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Extra resources for Reproducibility 
* https://pytorch.org/docs/stable/notes/randomness.html

* https://en.wikipedia.org/wiki/Random_seed

## Running tensors and pyTorch obj on the GPUs (fasterr)

GPUs = faster computation on numbers, CUDA + NVIDIA + PyTorch yeahh

### 1. Getting a GPUs

1. Easiest - Use colab for free GPUs

2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU for setup

  option: https://timdettmers.com/2023/01/16/which-gpu-for-deep-learning/

3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent compouters on the cloud and acces them.

For 2,3 PyTorch + GPU driver(CUDA) takes a little bit of setting up, to do this refer to Pytorch setup documentation. https://pytorch.org/


In [ ]:
!nvidia-smi

### 2. Check for GPU access with PyTorch

In [ ]:
# Check for GPU acces with PyTorch
import torch
torch.cuda.is_available()

True

from torch._C import PyTorchFileReader
For PyTorch since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code: http://pytorch.org/docs/stable/notes/cuda.html#best-practices

E.g. run on GPU if available else CPU

In [ ]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# Count the number of devices 
torch.cuda.device_count()

1

## 3. Putting tensors(and models ) on the GPU

The reason we want out tensor/models on the GPU is because using a GPU results in faster computations.

In [ ]:
# Create a tensor (default on CPU)

tensor = torch.tensor([1,2,3], device='cpu')

#Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
#Move tensor to GPU if avail
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensor back to CPU

In [ ]:
#If tensor is on GPU, cant transform it to Numpy
#tensor_on_gpu.numpy()

In [ ]:
#To fix gpu tensor with np issue, set to cpu
tensor_back_to_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_to_cpu

array([1, 2, 3])

In [ ]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

## Exercises

ref: https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises

In [ ]:
import torch
'''
[1] Documentation reading - A big part of deep learning (and learning to code in general) is 
getting familiar with the documentation of a certain framework you're using.
We'll be using the PyTorch documentation a lot throughout the rest of this course. 
So I'd recommend spending 10-minutes reading the following 
(it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness).
 See the documentation on torch.Tensor and for torch.cuda.
'''

'''
[2] Create a random tensor with shape (7, 7).
'''

tensor_A = torch.rand(7,7)

tensor_A

tensor([[0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783],
        [0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056]])

In [ ]:
'''
[3] Perform a matrix multiplication on the tensor from 2 with another 
random tensor with shape (1, 7) (hint: you may have to transpose the second tensor). 
'''
tensor_B = torch.rand(1,7)
tensor_C = torch.rand(1,7)

tensor_B.matmul(tensor_C.T)

tensor([[1.8807]])

In [ ]:
'''
[4] set the random seed to 0 and do ex 2,3 over again
'''
RAND_SEED = 0
#2
torch.manual_seed(RAND_SEED)
tensor_A = torch.rand(7,7)

#3
torch.manual_seed(RAND_SEED)
tensor_B = torch.rand(1,7)

torch.manual_seed(RAND_SEED)
tensor_C = torch.rand(1,7)

tensor_A, tensor_B, tensor_C

(tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
         [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
         [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
         [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
         [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
         [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
         [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]]),
 tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]]),
 tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]]))

In [ ]:
'''
[5] Speaking of random seeds, we saw how to set it with torch.manual_seed() but 
is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one). 
If there is, set the GPU random seed to 1234.
'''
device = "cuda" if torch.cuda.is_available() else "cpu"
device

RAND_SEED = 1234
torch.manual_seed(RAND_SEED)
tensor_A = torch.rand(7,7).to(device)

torch.manual_seed(RAND_SEED)
tensor_b = torch.rand(7,7).to(device)


tensor_A.device == tensor_B.device, tensor_A.device, tensor_B.device


(False, device(type='cuda', index=0), device(type='cpu'))

In [ ]:
'''
[6] Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). 
Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).
'''
torch.manual_seed(1234)
tensor_rand1 = torch.rand(2,3).to(device)

torch.manual_seed(1234)
tensor_rand2 = torch.rand(2,3).to(device)

tensor_rand1.device, tensor_rand2.device

(device(type='cuda', index=0), device(type='cuda', index=0))

In [ ]:
tensor_rand1, tensor_rand2

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'))

In [ ]:
'''
[7] Perform a matrix multiplication on the tensors you created in 6 
(again, you may have to adjust the shapes of one of the tensors).
'''
mm_tensor1_2 = tensor_rand1.mm(tensor_rand2.T)
mm_tensor1_2


tensor([[0.2299, 0.2161],
        [0.2161, 0.6287]], device='cuda:0')

In [ ]:
'''
[8] Find the maximum and minimum values of the output of 7.
'''
mm_tensor1_2.max(), mm_tensor1_2.min()

(tensor(0.6287, device='cuda:0'), tensor(0.2161, device='cuda:0'))

In [ ]:
'''
[9] Find the maximum and minimum index values of the output of 7.
'''
mm_tensor1_2.argmax(), mm_tensor1_2.argmin()

(tensor(3, device='cuda:0'), tensor(1, device='cuda:0'))

In [ ]:
'''
[10] Make a random tensor with shape (1, 1, 1, 10) 
and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). 
Set the seed to 7 when you create it and print out the first tensor and it's shape as 
well as the second tensor and it's shape.
'''
torch.manual_seed(7)
rand_tensor = torch.rand(1,1,1,10)
removed_dim_tensor = rand_tensor.squeeze()

rand_tensor, removed_dim_tensor

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]))